/*
Navicat MySQL Data Transfer

Source Server         : local
Source Server Version : 50532
Source Host           : localhost:3306
Source Database       : test

Target Server Type    : MYSQL
Target Server Version : 50532
File Encoding         : 65001

Date: 2013-12-04 00:19:16
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for test
-- ----------------------------
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `artnum` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `experience` varchar(255) DEFAULT NULL,
  `function` varchar(255) DEFAULT NULL,
  `employment` varchar(255) DEFAULT NULL,
  `education` varchar(255) DEFAULT NULL,
  `available` varchar(255) DEFAULT NULL,
  `hours` varchar(255) DEFAULT NULL,
  `salary` varchar(255) DEFAULT NULL,
  `description` longtext,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=261 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of test
-- ----------------------------
INSERT INTO `test` VALUES ('1', '43141946', 'Nationale Vacaturebank', 'Brummen', 'Ervaren', 'Vacature voor Key Accountmanager ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2943598/Key+Accountmanager/-15');
INSERT INTO `test` VALUES ('2', '43142112', 'Nationale Vacaturebank', 'Arnhem', 'Ervaren', 'Vacature voor Junior software consultant ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2943764/Junior+software+consultant/-14');
INSERT INTO `test` VALUES ('3', '43141698', 'Nationale Vacaturebank', 'Valkenswaard', 'Starter', 'Vacature voor ICT Service &amp; Beheer medewerker ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2943350/ICT+Service+%26+Beheer+medewerker/-13');
INSERT INTO `test` VALUES ('4', '43141278', 'Nationale Vacaturebank', 'Gorinchem', 'Ervaren', 'Vacature voor Toezichthouder Civiel ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942930/Toezichthouder+Civiel/-12');
INSERT INTO `test` VALUES ('5', '43141103', 'Nationale Vacaturebank', 'Hendrik-Ido-Ambacht', 'Ervaren', 'Vacature voor Field Service Engineer Hardware IT ', 'Vast', 'MBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942755/Field+Service+Engineer+Hardware+IT/-11');
INSERT INTO `test` VALUES ('6', '43141086', 'Nationale Vacaturebank', 'Gorinchem', 'Ervaren', 'Vacature voor Werkvoorbereider CAI/COAX/HFC ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942738/Werkvoorbereider+CAI%2FCOAX%2FHFC/-10');
INSERT INTO `test` VALUES ('7', '43141079', 'Nationale Vacaturebank', 'Arnhem', 'Ervaren', 'Vacature voor SAP Functioneel Analist SD/MM ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942731/SAP+Functioneel+Analist+SD%2FMM/-9');
INSERT INTO `test` VALUES ('8', '43140893', 'Nationale Vacaturebank', 'Stellendam', 'Ervaren', 'Vacature voor Software Engineer - G2 ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 1750 - 2500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2942545/Software+Engineer+-+G2/-8');
INSERT INTO `test` VALUES ('9', '43140885', 'Nationale Vacaturebank', 'Maarssen', 'Starter', 'Vacature voor Traineeship IT ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942537/Traineeship+IT/-7');
INSERT INTO `test` VALUES ('10', '43140779', 'Nationale Vacaturebank', '\'s-Gravenhage', 'Ervaren', 'Vacature voor Parttime Documentalist Steenbergen ', 'Tijdelijk', 'HBO', '', '24 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942431/Parttime+Documentalist+Steenbergen/-6');
INSERT INTO `test` VALUES ('11', '43140470', 'Nationale Vacaturebank', 'Eindhoven', 'Ervaren', 'Vacature voor Senior Systeembeheerder met virtuele / cloud ervaring in regio Eindhoven ', 'Vast', 'HBO', '', '36 - 40 uur per week', '€ 3200 - 3700 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2942122/Senior+Systeembeheerder+met+virtuele+%2F+cloud+ervaring+in+regio+Eindhoven/-5');
INSERT INTO `test` VALUES ('12', '43140427', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Java software ontwikkelaar met CMS affiniteit ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942079/Java+software+ontwikkelaar+met+CMS+affiniteit/-4');
INSERT INTO `test` VALUES ('13', '43140175', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Sales Consultant (New Business) ', 'Tijdelijk', 'HBO', '', '6 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2941827/Sales+Consultant+%28New+Business%29/-3');
INSERT INTO `test` VALUES ('14', '42952264', 'Nationale Vacaturebank', 'Drachten', 'Starter', 'Vacature voor Startende Software Engineer ', 'Vast', 'HBO', '', '36 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2753916/Startende+Software+Engineer/-2');
INSERT INTO `test` VALUES ('15', '43139850', 'Nationale Vacaturebank', 'Eindhoven', 'Starter', 'Vacature voor Callcenter medewerker helpdesk Eindhoven ', 'Tijdelijk', 'MBO', '', '32 - 40 uur per week', '€ 1547 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941502/Callcenter+medewerker+helpdesk+Eindhoven/-1');
INSERT INTO `test` VALUES ('16', '43141946', 'Nationale Vacaturebank', 'Brummen', 'Ervaren', 'Vacature voor Key Accountmanager ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2943598/Key+Accountmanager/0');
INSERT INTO `test` VALUES ('17', '43142112', 'Nationale Vacaturebank', 'Arnhem', 'Ervaren', 'Vacature voor Junior software consultant ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2943764/Junior+software+consultant/1');
INSERT INTO `test` VALUES ('18', '43141698', 'Nationale Vacaturebank', 'Valkenswaard', 'Starter', 'Vacature voor ICT Service &amp; Beheer medewerker ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2943350/ICT+Service+%26+Beheer+medewerker/2');
INSERT INTO `test` VALUES ('19', '43141278', 'Nationale Vacaturebank', 'Gorinchem', 'Ervaren', 'Vacature voor Toezichthouder Civiel ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942930/Toezichthouder+Civiel/3');
INSERT INTO `test` VALUES ('20', '43141103', 'Nationale Vacaturebank', 'Hendrik-Ido-Ambacht', 'Ervaren', 'Vacature voor Field Service Engineer Hardware IT ', 'Vast', 'MBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942755/Field+Service+Engineer+Hardware+IT/4');
INSERT INTO `test` VALUES ('21', '43141086', 'Nationale Vacaturebank', 'Gorinchem', 'Ervaren', 'Vacature voor Werkvoorbereider CAI/COAX/HFC ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942738/Werkvoorbereider+CAI%2FCOAX%2FHFC/5');
INSERT INTO `test` VALUES ('22', '43141079', 'Nationale Vacaturebank', 'Arnhem', 'Ervaren', 'Vacature voor SAP Functioneel Analist SD/MM ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942731/SAP+Functioneel+Analist+SD%2FMM/6');
INSERT INTO `test` VALUES ('23', '43140893', 'Nationale Vacaturebank', 'Stellendam', 'Ervaren', 'Vacature voor Software Engineer - G2 ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 1750 - 2500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2942545/Software+Engineer+-+G2/7');
INSERT INTO `test` VALUES ('24', '43140885', 'Nationale Vacaturebank', 'Maarssen', 'Starter', 'Vacature voor Traineeship IT ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942537/Traineeship+IT/8');
INSERT INTO `test` VALUES ('25', '43140779', 'Nationale Vacaturebank', '\'s-Gravenhage', 'Ervaren', 'Vacature voor Parttime Documentalist Steenbergen ', 'Tijdelijk', 'HBO', '', '24 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942431/Parttime+Documentalist+Steenbergen/9');
INSERT INTO `test` VALUES ('26', '43140470', 'Nationale Vacaturebank', 'Eindhoven', 'Ervaren', 'Vacature voor Senior Systeembeheerder met virtuele / cloud ervaring in regio Eindhoven ', 'Vast', 'HBO', '', '36 - 40 uur per week', '€ 3200 - 3700 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2942122/Senior+Systeembeheerder+met+virtuele+%2F+cloud+ervaring+in+regio+Eindhoven/10');
INSERT INTO `test` VALUES ('27', '43140427', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Java software ontwikkelaar met CMS affiniteit ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2942079/Java+software+ontwikkelaar+met+CMS+affiniteit/11');
INSERT INTO `test` VALUES ('28', '43140175', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Sales Consultant (New Business) ', 'Tijdelijk', 'HBO', '', '6 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2941827/Sales+Consultant+%28New+Business%29/12');
INSERT INTO `test` VALUES ('29', '42952264', 'Nationale Vacaturebank', 'Drachten', 'Starter', 'Vacature voor Startende Software Engineer ', 'Vast', 'HBO', '', '36 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2753916/Startende+Software+Engineer/13');
INSERT INTO `test` VALUES ('30', '43139850', 'Nationale Vacaturebank', 'Eindhoven', 'Starter', 'Vacature voor Callcenter medewerker helpdesk Eindhoven ', 'Tijdelijk', 'MBO', '', '32 - 40 uur per week', '€ 1547 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941502/Callcenter+medewerker+helpdesk+Eindhoven/14');
INSERT INTO `test` VALUES ('31', '43139615', 'Nationale Vacaturebank', 'Schiphol', 'Ervaren', 'Vacature voor Datacenter Engineer ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941267/Datacenter+Engineer/15');
INSERT INTO `test` VALUES ('32', '43139617', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Testlead ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4400 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941269/Testlead/16');
INSERT INTO `test` VALUES ('33', '43139607', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Thoughtleader Testen ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 0 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941259/Thoughtleader+Testen/17');
INSERT INTO `test` VALUES ('34', '43139609', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Thoughtleader Testen ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941261/Thoughtleader+Testen/18');
INSERT INTO `test` VALUES ('35', '43139603', 'Nationale Vacaturebank', 'Amsterdam', 'Ervaren', 'Vacature voor Technisch Applicatiebeheerder Ziekenhuis Informatie Systeem ', 'Vast', 'HBO', '', '32 - 36 uur per week', '€ 0 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941255/Technisch+Applicatiebeheerder+Ziekenhuis+Informatie+Systeem/19');
INSERT INTO `test` VALUES ('36', '43139462', 'Nationale Vacaturebank', 'Almere', 'Ervaren', 'Vacature voor BI Consultant SAS ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 0 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941114/BI+Consultant+SAS/20');
INSERT INTO `test` VALUES ('37', '43139362', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Javascript Guru ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 0 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941014/Javascript+Guru/21');
INSERT INTO `test` VALUES ('38', '43139325', 'Nationale Vacaturebank', 'Amsterdam', 'Ervaren', 'Vacature voor Controller - Application Manager ', 'Tijdelijk', 'HBO', '', '32 - 40 uur per week', '€ 3000 - 4000 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2940977/Controller+-+Application+Manager/22');
INSERT INTO `test` VALUES ('39', '42964324', 'Nationale Vacaturebank', 'Amsterdam', 'Starter', 'Vacature voor Uitdagende baan voor een (junior) front end developer ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2765976/Uitdagende+baan+voor+een+%28junior%29+front+end+developer/23');
INSERT INTO `test` VALUES ('40', '42957485', 'Nationale Vacaturebank', 'Hilversum', 'Ervaren', 'Vacature voor Ambitieuze PHP Ontwikkelaar (die op hoog niveau wil ontwikkelen) ', 'Vast', 'MBO', '', '32 - 40 uur per week', '€ 2500 - 3500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2759137/Ambitieuze+PHP+Ontwikkelaar+%28die+op+hoog+niveau+wil+ontwikkelen%29/24');
INSERT INTO `test` VALUES ('41', '42959990', 'Nationale Vacaturebank', 'AmsterdamZuidoost', 'Ervaren', 'Vacature voor Veelzijdige functie voor een slimme Software Developer (PHP) ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 2500 - 4000 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2761642/Veelzijdige+functie+voor+een+slimme+Software+Developer+%28PHP%29/25');
INSERT INTO `test` VALUES ('42', '43139272', 'Nationale Vacaturebank', '\'s-Gravenhage', 'Ervaren', 'Vacature voor Top voorwaarden vraagt ook om top .NET ontwikkelaars ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940924/Top+voorwaarden+vraagt+ook+om+top+.NET+ontwikkelaars/26');
INSERT INTO `test` VALUES ('43', '43139269', 'Nationale Vacaturebank', 'Deventer', 'Ervaren', 'Vacature voor Senior Oracle DBA (RAC, RMAN, Dataguard) ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940921/Senior+Oracle+DBA+%28RAC%2C+RMAN%2C+Dataguard%29/27');
INSERT INTO `test` VALUES ('44', '43139019', 'Nationale Vacaturebank', 'RijswijkZH', 'Ervaren', 'Vacature voor IT Solution Architect (ca 90.000,=) ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940671/IT+Solution+Architect+%28ca+90.000%2C%3D%29/28');
INSERT INTO `test` VALUES ('45', '43138994', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Sales Consultant Binnendienst ', 'Tijdelijk', 'HBO', '', '6 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940646/Sales+Consultant+Binnendienst/29');
INSERT INTO `test` VALUES ('46', '43138928', 'Nationale Vacaturebank', 'Arnhem', 'Ervaren', 'Vacature voor Business Informatie Analist ', 'Vast', 'HBO', '', '36 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940580/Business+Informatie+Analist/30');
INSERT INTO `test` VALUES ('47', '43138555', 'Nationale Vacaturebank', 'Twello', 'Starter', 'Vacature voor PHP Ontwikkelaar ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 1 - 2 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2940207/PHP+Ontwikkelaar/31');
INSERT INTO `test` VALUES ('48', '43139129', 'Nationale Vacaturebank', 'Hilversum', 'Ervaren', 'Vacature voor Application Consultant (procurement systemen) te Hilversum ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940781/Application+Consultant+%28procurement+systemen%29+te+Hilversum/32');
INSERT INTO `test` VALUES ('49', '43139166', 'Nationale Vacaturebank', 'Utrecht', 'Ervaren', 'Vacature voor SEA Specialist ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940818/SEA+Specialist/33');
INSERT INTO `test` VALUES ('50', '43139321', 'Nationale Vacaturebank', 'Utrecht', 'Ervaren', 'Vacature voor Duitse Marketeer ', 'Vast', 'HBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2940973/Duitse+Marketeer/34');
INSERT INTO `test` VALUES ('51', '43139346', 'Nationale Vacaturebank', 'Diemen', 'Ervaren', 'Vacature voor senior C# software developer - architect - innovatie in Amsterdam ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3100 - 4300 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2940998/senior+C%23+software+developer+-+architect+-+innovatie+in+Amsterdam/35');
INSERT INTO `test` VALUES ('52', '43139367', 'Nationale Vacaturebank', 'Rotterdam', 'Ervaren', 'Vacature voor Accountmanager New Business ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 2500 - 3000 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941019/Accountmanager+New+Business/36');
INSERT INTO `test` VALUES ('53', '43139691', 'Nationale Vacaturebank', 'Amstelveen', 'Ervaren', 'Vacature voor Sales Specialist Printing Solutions ', 'Vast', 'HBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2941343/Sales+Specialist+Printing+Solutions/37');
INSERT INTO `test` VALUES ('54', '43139601', 'Nationale Vacaturebank', 'Vlijmen', 'Ervaren', 'Vacature voor systeembeheerder (windows omgevingen) ', 'Vast', 'MBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2941253/systeembeheerder+%28windows+omgevingen%29/38');
INSERT INTO `test` VALUES ('55', '43139971', 'Nationale Vacaturebank', 'Amstelveen', 'Ervaren', 'Vacature voor Account Manager Binnendienst ', 'Vast', 'MBO', '', '40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2941623/Account+Manager+Binnendienst/39');
INSERT INTO `test` VALUES ('56', '43139968', 'Nationale Vacaturebank', 'Deurne', 'Starter', 'Vacature voor Telefoniste/ receptioniste ', 'Vast', 'MBO', '', '32 - 40 uur per week', 'Onderhandelbaar', null, 'http://www.nationalevacaturebank.nl/vacature/2941620/Telefoniste%2F+receptioniste/40');
INSERT INTO `test` VALUES ('57', '43139988', 'Nationale Vacaturebank', 'HengeloOV', 'Ervaren', 'Vacature voor Senior .NET Ontwikkelaar (die behoefte heeft aan stabiliteit) ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941640/Senior+.NET+Ontwikkelaar+%28die+behoefte+heeft+aan+stabiliteit%29/41');
INSERT INTO `test` VALUES ('58', '43140005', 'Nationale Vacaturebank', 'HengeloOV', 'Ervaren', 'Vacature voor SAP ABAP Ontwikkelaar (bijdrage leveren aan nieuwe afdeling) ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941657/SAP+ABAP+Ontwikkelaar+%28bijdrage+leveren+aan+nieuwe+afdeling%29/42');
INSERT INTO `test` VALUES ('59', '43140018', 'Nationale Vacaturebank', 'HengeloOV', 'Ervaren', 'Vacature voor Senior .NET Ontwikkelaar (bijdrage leveren aan nieuwe afdeling) ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941670/Senior+.NET+Ontwikkelaar+%28bijdrage+leveren+aan+nieuwe+afdeling%29/43');
INSERT INTO `test` VALUES ('60', '43139985', 'Nationale Vacaturebank', 'HengeloOV', 'Ervaren', 'Vacature voor SAP ABAP Ontwikkelaar (stabiele onderneming, stabiele afdeling) ', 'Vast', 'HBO', '', '32 - 40 uur per week', '€ 3500 - 4500 bruto per maand', null, 'http://www.nationalevacaturebank.nl/vacature/2941637/SAP+ABAP+Ontwikkelaar+%28stabiele+onderneming%2C+stabiele+afdeling%29/44');
INSERT INTO `test` VALUES ('61', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Gouda - Product Marketing Manager ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/product-marketing-manager');
INSERT INTO `test` VALUES ('62', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Hoorn - Jonge PHP5/Magento programmeur ', 'Bijbaan', 'HBO', '', '0 8 uur, 8 16 uur, 16 24 uur', '', null, 'http://www.jobselectie.nl/vacature/jonge-php5magento-programmeur');
INSERT INTO `test` VALUES ('63', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Hoorn - Fulltime PHP5/Magento programmeur ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/fulltime-php5magento-programmeur');
INSERT INTO `test` VALUES ('64', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Nijmegen - De nieuwste Java technieken! ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/de-nieuwste-java-technieken');
INSERT INTO `test` VALUES ('65', 'Geen', 'Jobselectie', '', '5 tot 10 jaar', '\nVacature \'s-Gravenhage - Technisch Consultant Citrix en RES ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/technisch-consultant-citrix-en-res');
INSERT INTO `test` VALUES ('66', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Eindhoven - Php programmeur / architect ', 'Vast', 'HBO', '', '16 24 uur, 24 32 uur, 32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/php-programmeur-architect');
INSERT INTO `test` VALUES ('67', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Arnhem - Ontwikkeling van bedrijfsportal (back- en frontend) in Arnhem ', 'Meeloopstage, Afstudeerstage', 'HBO', '', '0 8 uur, 8 16 uur', '', null, 'http://www.jobselectie.nl/vacature/ontwikkeling-van-bedrijfsportal-back-en-frontend-arnhem');
INSERT INTO `test` VALUES ('68', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Alkmaar - Stagiaire internet marketing PCI Alkmaar ', 'Meeloopstage, Afstudeerstage', 'HBO', '', '16 24 uur', '', null, 'http://www.jobselectie.nl/vacature/stagiaire-internet-marketing-pci-alkmaar');
INSERT INTO `test` VALUES ('69', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature IJsselstein - PHP PHP PHP programmeur regio Utrecht PHP PHP PHP ', 'Freelance, Vast', 'HBO', '', '16 24 uur', '', null, 'http://www.jobselectie.nl/vacature/php-php-php-programmeur-regio-utrecht-php-php-php');
INSERT INTO `test` VALUES ('70', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Gouda - Junior Software Engineer ', 'Vast', '', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/junior-software-engineer');
INSERT INTO `test` VALUES ('71', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Gouda - Technical Writer ', 'Vast', '', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/technical-writer');
INSERT INTO `test` VALUES ('72', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Gouda - Tester ', 'Vast', '', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/tester-1');
INSERT INTO `test` VALUES ('73', 'Geen', 'Jobselectie', '', '5 tot 10 jaar', '\nVacature \'s-Gravenhage - Accountmanager New Business - Randstad ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/accountmanager-new-business-randstad');
INSERT INTO `test` VALUES ('74', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature \'s-Gravenhage - Meer dan een systeembeheerder ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/meer-dan-een-systeembeheerder');
INSERT INTO `test` VALUES ('75', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Rotterdam - PHP Developer ', 'Vast', 'MBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/php-developer-0');
INSERT INTO `test` VALUES ('76', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Amsterdam - Software Engineer Interactive (m/v) ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/software-engineer-interactive-mv');
INSERT INTO `test` VALUES ('77', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Den Helder - Functioneel Beheerder PIMS (Proces Information Management System) ', 'Vast', 'MBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/functioneel-beheerder-pims-proces-information-management-system');
INSERT INTO `test` VALUES ('78', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Enschede - Sysadmin met passie in Enschede ', 'Bijbaan, Freelance', '', '', '0 8 uur, 8 16 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/sysadmin-met-passie-enschede');
INSERT INTO `test` VALUES ('79', 'Geen', 'Jobselectie', '', '5 tot 10 jaar', '\nVacature Zoetermeer - .NET Developer ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/net-developer');
INSERT INTO `test` VALUES ('80', '20120220-JXM', 'Jobselectie', 'Utrecht', '3 tot 5 jaar', '\nVacature Utrecht - Sr. Netwerk Consultant ', 'Vast', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/sr-netwerk-consultant');
INSERT INTO `test` VALUES ('81', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Enschede - Photoshop + CSS designer voor webshop ', 'Bijbaan, Thuiswerk', 'HBO', '', '0 8 uur', '', null, 'http://www.jobselectie.nl/vacature/photoshop-css-designer-voor-webshop');
INSERT INTO `test` VALUES ('82', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Heerenveen - Enthousiaste Web Developer gezocht ', 'Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/enthousiaste-web-developer-gezocht');
INSERT INTO `test` VALUES ('83', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Enschede - Mobile developer (8 tot 16 uur) ', 'Bijbaan, Vast, Tijdelijk', 'HBO', '', '8 16 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/mobile-developer-8-tot-16-uur');
INSERT INTO `test` VALUES ('84', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Amsterdam - Internet Search Evaluator - Dutch Speaking in Netherlands ', 'Freelance, Thuiswerk', '', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/internet-search-evaluator-dutch-speaking-netherlands');
INSERT INTO `test` VALUES ('85', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Rotterdam - Internet Search Evaluator - Dutch Speaking anywhere in Netherlands ', 'Tijdelijk', '', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/internet-search-evaluator-dutch-speaking-anywhere-netherlands');
INSERT INTO `test` VALUES ('86', '20121025-FCPY', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Rijssen - PHP Developer die door wil groeien ', 'Vast', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/php-developer-die-door-wil-groeien');
INSERT INTO `test` VALUES ('87', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Breda - Sales Medewerker Binnendienst ', 'Vast, Tijdelijk', 'HBO', '', '24 32 uur, 32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/sales-medewerker-binnendienst-0');
INSERT INTO `test` VALUES ('88', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Enschede - Vacature senior Drupal developer Enschede ', 'Vast', 'HBO', '', '16 24 uur, 24 32 uur, 32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/vacature-senior-drupal-developer-enschede');
INSERT INTO `test` VALUES ('89', '20120201-JCEE', 'Jobselectie', 'Utrecht', '3 tot 5 jaar', '\nVacature Utrecht - ASP.NET developer ', 'Vast', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/aspnet-developer-3');
INSERT INTO `test` VALUES ('90', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Enschede - Afstudeerstage webdevelopment in Enschede per februari 2014 ', 'Meeloopstage, Afstudeerstage', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/afstudeerstage-webdevelopment-enschede-februari-2014');
INSERT INTO `test` VALUES ('91', 'Geen', 'Jobselectie', 'Utrecht', '3 tot 5 jaar', '\nVacature Utrecht - Java Ontwikkelaar: doe wat je leuk vindt en goed in bent! ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/java-ontwikkelaar-doe-wat-je-leuk-vindt-en-goed-bent');
INSERT INTO `test` VALUES ('92', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Zwolle - PHP programmeur ', 'Vast', 'MBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/php-programmeur-0');
INSERT INTO `test` VALUES ('93', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Naarden - Technisch support medewerker (m/v) ', 'Vast', 'MBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/technisch-support-medewerker-mv');
INSERT INTO `test` VALUES ('94', 'Geen', 'Jobselectie', '', '5 tot 10 jaar', '\nVacature Vianen - ICT Specialist ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/ict-specialist');
INSERT INTO `test` VALUES ('95', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Barneveld - Asset Manager Windenergie ', 'Meeloopstage, Afstudeerstage, Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/asset-manager-windenergie');
INSERT INTO `test` VALUES ('96', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Nijmegen - Junior Projectleider ', 'Vast', 'HBO', '', '24 32 uur, 32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/junior-projectleider');
INSERT INTO `test` VALUES ('97', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Amsterdam - E-mail Marketeer ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/e-mail-marketeer');
INSERT INTO `test` VALUES ('98', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Rotterdam - SAP FICO BEHEERDER ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/sap-fico-beheerder');
INSERT INTO `test` VALUES ('99', 'Geen', 'Jobselectie', 'Utrecht', '3 tot 5 jaar', '\nVacature Utrecht - JEE Developer: doe wat je leuk vindt en goed in bent! ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/jee-developer-doe-wat-je-leuk-vindt-en-goed-bent');
INSERT INTO `test` VALUES ('100', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Hilversum - Traffic &amp; Planning medewerker ', 'Vast', 'MBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/traffic-planning-medewerker');
INSERT INTO `test` VALUES ('101', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Enschede - Senior developer in Enschede ', 'Vast', 'HBO', '', '24 32 uur, 32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/senior-developer-enschede');
INSERT INTO `test` VALUES ('102', 'Geen', 'Jobselectie', 'Utrecht', 'minder dan 1 jaar', '\nVacature Utrecht - Junior C#/.Net Developer ', 'Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/junior-cnet-developer');
INSERT INTO `test` VALUES ('103', 'Geen', 'Jobselectie', 'Utrecht', '3 tot 5 jaar', '\nVacature Utrecht - Medior C#/.NET Developer ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/medior-cnet-developer');
INSERT INTO `test` VALUES ('104', 'Geen', 'Jobselectie', 'Utrecht', '5 tot 10 jaar', '\nVacature Utrecht - Senior C#/.NET Developer ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/senior-cnet-developer');
INSERT INTO `test` VALUES ('105', 'Geen', 'Jobselectie', 'Utrecht', '1 tot 3 jaar', '\nVacature Utrecht - Medior Front-end Developer ', 'Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/medior-front-end-developer');
INSERT INTO `test` VALUES ('106', 'Geen', 'Jobselectie', 'Utrecht', '5 tot 10 jaar', '\nVacature Utrecht - Senior Front-end Developer ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/senior-front-end-developer');
INSERT INTO `test` VALUES ('107', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature \'s-Hertogenbosch - .NET/WEB Developer met passie gezocht! ', 'Vast', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/netweb-developer-met-passie-gezocht');
INSERT INTO `test` VALUES ('108', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Mierlo - SOFTWARE ENGINEERS .NET ', 'Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/software-engineers-net');
INSERT INTO `test` VALUES ('109', '20130313-EFPG', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Sliedrecht - Informatie Analist ', 'Vast', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/informatie-analist-1');
INSERT INTO `test` VALUES ('110', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature Zoetermeer - Medior .NET Developer Roxit Zoetermeer ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/medior-net-developer-roxit-zoetermeer');
INSERT INTO `test` VALUES ('111', 'Geen', 'Jobselectie', '', '5 tot 10 jaar', '\nVacature Zoetermeer - Teamlead - Leaddeveloper .NET Roxit ', 'Vast, Tijdelijk', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/teamlead-leaddeveloper-net-roxit');
INSERT INTO `test` VALUES ('112', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Amsterdam Zuidoost - Freelance top sales / verkoper -vertegenwoordiger gezocht ', 'Freelance, ZZP, Franchise', 'MBO', '', '0 8 uur, 16 24 uur, 32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/freelance-top-sales-verkoper-vertegenwoordiger-gezocht');
INSERT INTO `test` VALUES ('113', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Nijverdal - app developer ', 'Freelance, ZZP, Tijdelijk', 'MBO', '', '16 24 uur', '', null, 'http://www.jobselectie.nl/vacature/app-developer-0');
INSERT INTO `test` VALUES ('114', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature \'s-Gravenhage - Gamedeveloper (C#) ', 'Vast', 'HBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/gamedeveloper-c');
INSERT INTO `test` VALUES ('115', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Roermond - System Application Engineer. ', 'Vast', 'MBO', '', '32 40 uur', '- € 2500 - € 3500', null, 'http://www.jobselectie.nl/vacature/system-application-engineer');
INSERT INTO `test` VALUES ('116', 'Geen', 'Jobselectie', '', '1 tot 3 jaar', '\nVacature Hengelo - (ervaren) PHP-programmeur(s) ', 'Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/ervaren-php-programmeurs');
INSERT INTO `test` VALUES ('117', 'Geen', 'Jobselectie', 'Utrecht', 'minder dan 1 jaar', '\nVacature Utrecht - IT trainee ', 'Interim, Vast', 'HBO', '', '32 40 uur', '- € 1750 - € 2500', null, 'http://www.jobselectie.nl/vacature/it-trainee');
INSERT INTO `test` VALUES ('118', '20120209-BJHB', 'Jobselectie', 'Utrecht', '5 tot 10 jaar', '\nVacature Utrecht - Project Engineer Backoffice (Microsoft/VMware) ', 'Vast', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/project-engineer-backoffice-microsoftvmware');
INSERT INTO `test` VALUES ('119', 'Geen', 'Jobselectie', '', '3 tot 5 jaar', '\nVacature \'s-Hertogenbosch - Implementatieconsultant met stevige technische bagage ', 'Vast, Tijdelijk', 'HBO', '', '32 40 uur', '- € 3500 - € 5000', null, 'http://www.jobselectie.nl/vacature/implementatieconsultant-met-stevige-technische-bagage');
INSERT INTO `test` VALUES ('120', 'Geen', 'Jobselectie', '', 'minder dan 1 jaar', '\nVacature Amsterdam - Developer stagiair(e) gezocht! ', 'Meeloopstage', 'HBO', '', '32 40 uur', '', null, 'http://www.jobselectie.nl/vacature/developer-stagiaire-gezocht');
INSERT INTO `test` VALUES ('121', '2791137', 'Jobbird', 'Nederland', '', 'Topbaan: Network Engineer', '', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2791137/network-engineer-bij-careermaker-in-amsterdam');
INSERT INTO `test` VALUES ('122', '2786889', 'Jobbird', 'Nederland', '', 'Topbaan: Telecom monteur', '', 'MBO', '', '32-40 uur', '', null, '/nl/vacature/2786889/telecom-monteur-bij-careermaker-in-amsterdam');
INSERT INTO `test` VALUES ('123', '1661235', 'Jobbird', 'Utrecht', '', 'Topbaan: Senior Field Engineer Antennebouw', 'Vast', 'MBO', '', '32-40 uur', '', null, '/nl/vacature/1661235/senior-field-engineer-antennebouw-bij-careermaker-in-hooglanderveen');
INSERT INTO `test` VALUES ('124', '2828983', 'Jobbird', 'Noord-Holland, Utrecht, Zuid-Holland', '3-5 jaar, 5-10 jaar', 'Topbaan: (Senior) Marketing & Sales', 'Uitzenden/Tijdelijk', 'HBO, HAVO', '', '32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2828983/senior-marketing-amp-sales-bij-chuango-europe-b-v-in-hoofddorp');
INSERT INTO `test` VALUES ('125', '2847316', 'Jobbird', 'Noord-Holland, Utrecht, Zuid-Holland', '3-5 jaar, 5-10 jaar', 'Topbaan: Technical & Support Engineer', 'Uitzenden/Tijdelijk', 'MBO, HBO', '', '32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2847316/technical-en-support-engineer-bij-chuango-europe-b-v-in-hoofddorp');
INSERT INTO `test` VALUES ('126', '2841321', 'Jobbird', 'Noord-Brabant', '0 (Starter)', 'Topbaan: SEA consultant (32 - 40 uur)', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2841321/sea-consultant-32-40-uur-bij-teleperformance-in-tilburg');
INSERT INTO `test` VALUES ('127', '2308810', 'Jobbird', '', '', 'Topbaan: Monteur CAI', '', 'MBO', '', '32-40 uur', '', null, '/nl/vacature/2308810/monteur-cai-bij-careermaker-in-amsterdam');
INSERT INTO `test` VALUES ('128', '2750381', 'Jobbird', 'Noord-Holland, Flevoland, Zuid-Holland', '3-5 jaar, 10 jaar of meer', 'Topbaan: Linux System Engineer', 'Vast', 'HBO, Universitair', '', '32-40 uur', '€ 5000 - en meer', null, '/nl/vacature/2750381/linux-system-engineer-bij-midassearch-in-lelystad');
INSERT INTO `test` VALUES ('129', '2611435', 'Jobbird', 'Noord-Brabant, Utrecht, Zuid-Holland', '3-5 jaar', 'Topbaan: Hoofd financiele administrate', 'Vast', 'MBO, HBO', '', '32-40 uur', '', null, '/nl/vacature/2611435/medewerker-financiele-administrate-bij-monkey-tail-bv-in-oosterhout-nb');
INSERT INTO `test` VALUES ('130', '2801193', 'Jobbird', 'Zuid-Holland', '', 'Topbaan: junior onsite engineer service', '', 'VMBO / MAVO', '', '32-40 uur', '', null, '/nl/vacature/2801193/junior-onsite-engineer-service-bij-careermaker-in-rotterdam');
INSERT INTO `test` VALUES ('131', '1534100', 'Jobbird', '', '', 'Topbaan: Field Service Engineer KPN SOLC', 'Vast', 'VMBO / MAVO', '', '32-40 uur', '', null, '/nl/vacature/1534100/field-service-engineer-kpn-solc-bij-careermaker-in-rotterdam');
INSERT INTO `test` VALUES ('132', '2816228', 'Jobbird', 'Noord-Holland', '3-5 jaar, 1-3 jaar', 'Topbaan: Account Manager', 'Vast', 'MBO', '', '32-40 uur', '', null, '/nl/vacature/2816228/account-manager-in-hoofddorp');
INSERT INTO `test` VALUES ('133', '2823417', 'Jobbird', 'Noord-Holland, Utrecht, Gelderland', '3-5 jaar, 1-3 jaar', 'Topbaan: BtoB Accountmanager Binnendienst Automotive Utrecht', 'Vast', 'HBO, MBO', '', '32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2823417/btob-accountmanager-binnendienst-automotive-utrecht-bij-spn-sales-pro-nederland-in-utrecht');
INSERT INTO `test` VALUES ('134', '2822489', 'Jobbird', 'Drenthe, Friesland, Groningen', '5-10 jaar', 'Topbaan: Financieel Controller', 'Vast', 'HBO, Universitair', '', '32-40 uur', '€ 3500 - € 5000', null, '/nl/vacature/2822489/financieel-controller-bij-brainconsultant-recruiters-finance-amp-ict-jij-techniek-in-groningen');
INSERT INTO `test` VALUES ('135', '2821633', 'Jobbird', 'Utrecht', '3-5 jaar, 5-10 jaar', 'Topbaan: Software Developer ASP.NET', 'Vast', 'Universitair, HBO', '', '32-40 uur', '', null, '/nl/vacature/2821633/software-developer-asp-net-bij-unit4-in-sliedrecht');
INSERT INTO `test` VALUES ('136', '2696526', 'Jobbird', 'Limburg, Noord-Brabant, Gelderland', '3-5 jaar, 5-10 jaar', 'Topbaan: Vacature Support Engineer / Remote Systeembeheerder Eindhoven (40 uur)', 'Vast', 'HBO, MBO', '', '32-40 uur', '', null, '/nl/vacature/2696526/vacature-support-engineer-remote-systeembeheerder-eindhoven-40-uur-bij-ictivity-groep-b-v-in-eindhoven');
INSERT INTO `test` VALUES ('137', '2554638', 'Jobbird', 'Nederland', '1-3 jaar, 3-5 jaar', 'Topbaan: Receptioniste / Projectsecretaresse / Traffic Manager Internetbureau', 'Vast', 'VWO, HBO', '', '32-40 uur', '€ 1750 - € 2500', null, '/nl/vacature/2554638/projectsecretaresse-traffic-manager-in-capelle-aan-den-ijssel');
INSERT INTO `test` VALUES ('138', '2604664', 'Jobbird', 'Groningen', '1-3 jaar, 3-5 jaar', 'Topbaan: Experienced  SAP basis developer at IBM Services Center Benelux', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2604664/experienced-sap-basis-developer-at-ibm-services-center-benelux-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('139', '2787533', 'Jobbird', 'Zuid-Holland', '3-5 jaar, 5-10 jaar', 'Topbaan: Office Manager bij ICT bedrijf (24 tot 32 uur per week)', 'Vast', 'HBO, Universitair', '', '24-32 uur, 32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2787533/office-manager-bij-ict-bedrijf-24-tot-32-uur-per-week-bij-fortezza-ict-in-den-haag');
INSERT INTO `test` VALUES ('140', '2781284', 'Jobbird', 'Nederland', '3-5 jaar, 5-10 jaar', 'Topbaan: Functioneel Analist/Ontwerper (32 uur)', 'Vast', 'HBO', '', '24-32 uur, 32-40 uur', '', null, '/nl/vacature/2781284/functioneel-analist-ontwerper-32-uur-bij-naktuinbouw-in-roelofarendsveen');
INSERT INTO `test` VALUES ('141', '2781601', 'Jobbird', 'Noord-Brabant', '3-5 jaar, 5-10 jaar', 'Topbaan: XML expert freelance/ vaste functie', 'Freelance', 'HBO', '', '32-40 uur, 24-32 uur', '', null, '/nl/vacature/2781601/xml-expert-freelance-vaste-functie-bij-dct-in-helmond');
INSERT INTO `test` VALUES ('142', '2664153', 'Jobbird', 'Groningen', '1-3 jaar, 0 (Starter)', 'Topbaan: Embedded Software Engineer', 'Uitzenden/Tijdelijk', 'HBO, Universitair', '', '24-32 uur, 32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2664153/embedded-systems-engineer-bij-tvilight-bv-in-groningen');
INSERT INTO `test` VALUES ('143', '2732521', 'Jobbird', 'Drenthe, Friesland, Groningen', '5-10 jaar', 'Topbaan: Enthousiaste Accountmanager ICT Infrastructuur / Cloud Service', 'Vast', 'HBO', '', '32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2732521/enthousiaste-accountmanager-ict-infrastructuur-cloud-service-bij-arrix-in-drachten');
INSERT INTO `test` VALUES ('144', '2570762', 'Jobbird', 'Nederland', '0 (Starter)', 'Topbaan: Linux Engineer', 'Vast', 'MBO, HBO', '', '32-40 uur', '', null, '/nl/vacature/2570762/linux-engineer-bij-oblatio-recruitment-in-culemborg');
INSERT INTO `test` VALUES ('145', '2732101', 'Jobbird', 'Drenthe, Overijssel, Nederland', '3-5 jaar, 5-10 jaar', 'Topbaan: PHP Programmeur/ Developer', 'Vast', 'HBO, MBO', '', '32-40 uur', '', null, '/nl/vacature/2732101/php-programmeur-developer-bij-fizz-ondernemers-in-marketing-amp-communicatie-in-meppel');
INSERT INTO `test` VALUES ('146', '1746949', 'Jobbird', 'Gelderland, Noord-Brabant, Nederland', '5-10 jaar, 10 jaar of meer', 'Topbaan: Software Engineer .Net C# ', 'Vast', 'HBO, Universitair', '', '32-40 uur', '', null, '/nl/vacature/1746949/software-engineer-net-c-bij-iquality-in-nijmegen');
INSERT INTO `test` VALUES ('147', '2741717', 'Jobbird', 'Utrecht, Noord-Holland, Zuid-Holland', '3-5 jaar, 5-10 jaar', 'Topbaan: NoProtocol zoekt Web Developer', 'Vast', 'HBO, Universitair', '', '32-40 uur', '', null, '/nl/vacature/2741717/noprotocol-zoekt-web-developer-bij-noprotocol-in-amsterdam');
INSERT INTO `test` VALUES ('148', '2600521', 'Jobbird', 'Groningen', '3-5 jaar, 5-10 jaar', 'Topbaan: Junior, medior and senior Oracle Forms Developer at IBM Service Center ', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2600521/experienced-oracle-forms-developer-at-ibm-services-center-benelux-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('149', '2577584', 'Jobbird', 'Groningen', '3-5 jaar, 5-10 jaar', 'Topbaan: Oracle Environment Manager at IBM Services Center Benelux', 'Vast', 'HBO, Universitair', '', '32-40 uur', '', null, '/nl/vacature/2577584/oracle-environment-manager-at-ibm-services-center-benelux-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('150', '2600993', 'Jobbird', 'Groningen', '1-3 jaar, 3-5 jaar', 'Topbaan: Experienced (medior) Websphere Application Developer at IBM Services Center', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2600993/experienced-medior-websphere-application-developer-at-ibm-services-center-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('151', '2710873', 'Jobbird', 'Utrecht, Zuid-Holland', '1-3 jaar, 3-5 jaar', 'Topbaan: Junior Java Software Ontwikkelaar', 'Uitzenden/Tijdelijk', 'Universitair, HBO', '', '32-40 uur', '€ 1750 - € 2500', null, '/nl/vacature/2710873/junior-java-software-ontwikkelaar-in-utrecht');
INSERT INTO `test` VALUES ('152', '2584963', 'Jobbird', 'Gelderland, Utrecht, Overijssel', '1-3 jaar, 3-5 jaar', 'Topbaan: Divitel zoekt een Accountmanager Media Broadcasting - Apeldoorn', 'Vast', 'HBO, Universitair', '', '32-40 uur', '', null, '/nl/vacature/2584963/divitel-zoekt-een-accountmanager-media-broadcasting-apeldoorn-bij-ryp-b-v-in-amsterdam');
INSERT INTO `test` VALUES ('153', '2689594', 'Jobbird', 'Utrecht', '0 (Starter), 1-3 jaar', 'Topbaan: Programmeur Beeldherkenning', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2689594/programmeur-beeldherkenning-bij-studio-diip-in-leerdam');
INSERT INTO `test` VALUES ('154', '2665103', 'Jobbird', 'Nederland, Gelderland, Utrecht', '3-5 jaar, 1-3 jaar', 'Topbaan: Business Systems Administrator', 'Vast', 'HBO, MBO', '', '32-40 uur', '', null, '/nl/vacature/2665103/business-systems-administrator-bij-technetix-bv-in-veenendaal');
INSERT INTO `test` VALUES ('155', '2664152', 'Jobbird', 'Overijssel', '1-3 jaar, 3-5 jaar', 'Topbaan: SEO en SEA Internet Marketeer (38 uur)', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2664152/seo-en-sea-internet-marketeer-38-uur-in-enschede');
INSERT INTO `test` VALUES ('156', '2607803', 'Jobbird', 'Drenthe, Friesland, Groningen', '3-5 jaar, 5-10 jaar', 'Topbaan: Vacature System Engineer m/v', 'Vast', 'HBO, MBO', '', '32-40 uur', '', null, '/nl/vacature/2607803/vacature-system-engineer-m-v-bij-danthas-bv-in-drachten');
INSERT INTO `test` VALUES ('157', '2490639', 'Jobbird', 'Noord-Holland, Gelderland', '1-3 jaar, 0 (Starter)', 'Topbaan: Accountmanager Corporate (binnendienst sales)', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2490639/account-manager-corporate-binnendienst-sales-bij-insight-enterprises-nehterlands-b-v-in-amsterdam');
INSERT INTO `test` VALUES ('158', '2655720', 'Jobbird', 'Flevoland', '1-3 jaar, 3-5 jaar', 'Topbaan: Helpdesk Medewerker voor het project Ziggo', 'Uitzenden/Tijdelijk', 'MBO, HBO', '', '16-24 uur', '', null, '/nl/vacature/2655720/helpdesk-medewerker-ziggo-almere-bij-xerox-in-almere');
INSERT INTO `test` VALUES ('159', '2657537', 'Jobbird', 'Noord-Brabant', '5-10 jaar', 'Topbaan: Vacature Senior PHP developer', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2657537/vacature-senior-php-developer-in-s-hertogenbosch');
INSERT INTO `test` VALUES ('160', '2656003', 'Jobbird', 'Nederland, België', '0 (Starter), 1-3 jaar', 'Topbaan: Commercieel medewerker met verstand van koeien voeren ', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2656003/commercieel-medewerker-met-verstand-van-koeien-voeren-in-assen');
INSERT INTO `test` VALUES ('161', '2606418', 'Jobbird', 'Australië', '5-10 jaar', 'Topbaan: Senior SAP ABAP Developer (Case Management, Social Services and/or WCEM)', 'Vast', 'Universitair', '', '32-40 uur', '', null, '/nl/vacature/2606418/senior-sap-abap-developer-case-management-social-services-and-or-wcem-bij-dialog-information-technology-in-brisbane');
INSERT INTO `test` VALUES ('162', '2651678', 'Jobbird', 'Drenthe', '3-5 jaar, 5-10 jaar', 'Topbaan: Software Engineer (f/m)', 'Uitzenden/Tijdelijk', 'Universitair, HBO', '', '32-40 uur', '', null, '/nl/vacature/2651678/software-engineer-f-m-in-dwingeloo');
INSERT INTO `test` VALUES ('163', '2026442', 'Jobbird', 'Nederland', '3-5 jaar, 5-10 jaar', 'Topbaan: Middleware Specialisten gezocht!', 'Vast', 'Universitair, HBO', '', '32-40 uur', '', null, '/nl/vacature/2026442/middleware-specialisten-gezocht-bij-axxius-in-hoofddorp');
INSERT INTO `test` VALUES ('164', '2600625', 'Jobbird', 'Groningen', '3-5 jaar, 1-3 jaar', 'Topbaan: Experienced Data Specialist Master Data Management at IBM Services', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2600625/experienced-data-specialist-master-data-management-at-ibm-services-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('165', '2603764', 'Jobbird', 'Groningen', '1-3 jaar, 3-5 jaar', 'Topbaan: Experienced Java Developer at IBM Services Center Benelux', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2603764/experienced-java-developer-at-ibm-services-center-benelux-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('166', '2604897', 'Jobbird', 'Groningen', '1-3 jaar, 3-5 jaar', 'Topbaan: Experienced Microsoft SharePoint Developer at IBM Services Center ', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2604897/experienced-microsoft-sharepoint-developer-at-ibm-services-center-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('167', '2604851', 'Jobbird', 'Groningen', '1-3 jaar, 5-10 jaar', 'Topbaan: Experienced  Application Developer - SAP ABAP at IBM Services Cente', 'Vast', 'HBO', '', '32-40 uur', '', null, '/nl/vacature/2604851/experienced-application-developer-sap-abap-at-ibm-services-cente-bij-ibm-in-rotterdam');
INSERT INTO `test` VALUES ('168', '2615170', 'Jobbird', 'Groningen', '1-3 jaar, 3-5 jaar', 'Topbaan: Experienced (medior) Data Specialist ETL Datastage at IBM Services Center', 'Vast', 'HBO, Universitair', '', '32-40 uur', '', null, '/nl/vacature/2615170/experienced-medior-data-specialist-etl-datastage-at-ibm-services-center-bij-ibm-in-groningen');
INSERT INTO `test` VALUES ('169', '2643772', 'Jobbird', 'Noord-Brabant', '0 (Starter), 3-5 jaar', 'Topbaan: Medewerker Sales Binnendienst, Business to Business', 'Vast', 'HBO, MBO', '', '32-40 uur', '€ 2500 - € 3500', null, '/nl/vacature/2643772/medewerker-sales-binnendienst-business-to-business-bij-techaccess-value-added-it-distribution-in-son');
INSERT INTO `test` VALUES ('170', '889060', 'Jobbird', 'Utrecht', '1-3 jaar, 3-5 jaar', 'Topbaan: IT-specialist documentatieontwikkeling', 'Vast', 'HBO, Universitair', '', '32-40 uur', '', null, '/nl/vacature/889060/lokalisatie-documentatie-engineer-bij-wcs-group-leaders-in-language-in-veenendaal');
INSERT INTO `test` VALUES ('171', '9124396', 'ItJobboard', 'Den Haag', '', 'SAP Stream Lead', 'Freelance', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/SAP-Stream-Lead/9124396/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('172', '9124392', 'ItJobboard', 'Zuid-Holland', '', 'Senior Information Security Specialist -Zuid Holland -Permanent', 'Vast', 'WO, HBO', '', '', '€70000 - €85000 per annum + Pension, Holidays,', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Information-Security-Specialist-Zuid-Holland-Permanent/9124392/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('173', '9117999', 'ItJobboard', 'Amsterdam', '', 'PHP Ontwikkelaar', 'Vast', 'WO, HBO', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/PHP-Ontwikkelaar/9117999/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('174', '9124300', 'ItJobboard', 'Antwerpen', '', 'Senior Software Engineer C++ (OpenGL) / Intern / Mechelen', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Software-Engineer-C-OpenGL-Intern-Mechelen/9124300/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('175', '9124297', 'ItJobboard', 'Den Haag', '', 'Do you have experience with CQRS/ES and ASP.NET MVC?', 'Vast', 'Onbekend', '', '', '€50000 - €80000 per annum + outstanding secundairy benefits', null, 'http://www.itjobboard.nl/ICT-baan/Do-you-have-experience-with-CQRSES-and-ASPNET-MVC/9124297/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('176', '9104964', 'ItJobboard', 'Utrecht', '', 'ASP.NET Developer', 'Vast', 'Onbekend', '', '', 'goede primaire én secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/ASPNET-Developer/9104964/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('177', '9104963', 'ItJobboard', 'Sliedrecht', '', '(Junior/Medior) .NET Software Developer', 'Vast', 'Onbekend', '', '', 'goede primaire én secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/JuniorMedior-NET-Software-Developer/9104963/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('178', '9123983', 'ItJobboard', 'Beerse', '', 'Clinical Data Standards Specialist', 'Freelance', 'Onbekend', '', '', '€0 - €60 per uur', null, 'http://www.itjobboard.nl/ICT-baan/Clinical-Data-Standards-Specialist/9123983/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('179', '9124367', 'ItJobboard', 'Amsterdam', '', 'Java Ontwikkelaar - Amsterdam - 50.000 - 55.000 euro- 36 uur', 'Vast', 'HBO', '', '', '€45000 - €55000 per annum + 45 vakantiedagen, pensioen,', null, 'http://www.itjobboard.nl/ICT-baan/Java-Ontwikkelaar-Amsterdam-50000-55000-euro-36-uur/9124367/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('180', '9124376', 'ItJobboard', 'Amsterdam', '', 'Sales Consultant', 'Freelance', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Sales-Consultant/9124376/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('181', '9124372', 'ItJobboard', 'Rotterdam', '', 'Microsoft/VMware System Administrator- Rotterdam -', 'Vast', 'MBO', '', '', '€45000 - €55000 per annum + benefits', null, 'http://www.itjobboard.nl/ICT-baan/MicrosoftVMware-System-Administrator-Rotterdam-/9124372/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('182', '8901408', 'ItJobboard', 'Amsterdam', '', 'C++ Software Engineer', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/C-Software-Engineer/8901408/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('183', '9112956', 'ItJobboard', 'regio Antwerpen', '', 'Java J2EE Developer', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Java-J2EE-Developer/9112956/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('184', '9078280', 'ItJobboard', 'Eindhoven', '', 'Front-End developer (HTML5,  CSS3, Javascript en jquery)', 'Vast', 'HBO', '', '', 'Aantrekkelijk salaris + bonusregeling en 32 vakantie dagen en', null, 'http://www.itjobboard.nl/ICT-baan/FrontEnd-developer-HTML5-CSS3-Javascript-en-jquery/9078280/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('185', '9084938', 'ItJobboard', 'Amsterdam', '', 'Websphere / MQ Specialist', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Websphere-MQ-Specialist/9084938/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('186', '9092675', 'ItJobboard', 'Haarlem', '', 'Hosting Engineer', 'Vast', 'Onbekend', '', '', 'Competitive', null, 'http://www.itjobboard.nl/ICT-baan/Hosting-Engineer/9092675/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('187', '9082590', 'ItJobboard', 'UTRECHT', '', 'Systeembeheerder windows  ( systeem beheerder ) - Utrecht', 'Vast', 'Onbekend', '', '', 'maximaal € 2.953,-', null, 'http://www.itjobboard.nl/ICT-baan/Systeembeheerder-windows-systeem-beheerder-Utrecht/9082590/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('188', '9114484', 'ItJobboard', 'Amersfoort', '', 'Senior Business Analyst', 'Vast', 'WO, HBO', '', '', 'Attractive conditions & benefits', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Business-Analyst/9114484/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('189', '9114486', 'ItJobboard', 'Amersfoort', '', 'Senior Technical Network Consultant Connectivity', 'Vast', 'Onbekend', '', '', 'Attractive conditions & benefits', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Technical-Network-Consultant-Connectivity/9114486/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('190', '8887002', 'ItJobboard', 'Amsterdam', '', 'Trading Software Developer', 'Vast', 'Onbekend', '', '', 'Competitive salary plus excellent benefits', null, 'http://www.itjobboard.nl/ICT-baan/Trading-Software-Developer/8887002/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('191', '9114488', 'ItJobboard', 'Amsterdam', '', 'SAP FI Specialist - Amsterdam (SAP FI-GL, AA, AR and AP)', 'Vast', 'Onbekend', '', '', 'Conform', null, 'http://www.itjobboard.nl/ICT-baan/SAP-FI-Specialist-Amsterdam-SAP-FIGL-AA-AR-and-AP/9114488/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('192', '9068446', 'ItJobboard', 'Utrecht', '', 'Junior PHP Ontwikkelaar (CSS, (X)HTML, XML,  Javascript en SQL)', 'Vast', 'HBO', '', '', 'Aantrekkelijke secundaire voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Junior-PHP-Ontwikkelaar-CSS-XHTML-XML-Javascript-en-SQL/9068446/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('193', '9112474', 'ItJobboard', 'Wormer', '', 'SAP FICO Consultant', 'Vast', 'Onbekend', '', '', 'Competitive compensation & benefit package', null, 'http://www.itjobboard.nl/ICT-baan/SAP-FICO-Consultant/9112474/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('194', '8654633', 'ItJobboard', 'Amsterdam', '', 'Microstrategy Professional - ( MicroStrategy, BI ) - Amsterdam', 'Vast', 'HBO', '', '', '€0 - €60.000 per jaar', null, 'http://www.itjobboard.nl/ICT-baan/Microstrategy-Professional-MicroStrategy-BI-Amsterdam/8654633/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('195', '8313458', 'ItJobboard', 'Amsterdam', '', 'System Performance Engineer', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/System-Performance-Engineer/8313458/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('196', '9114031', 'ItJobboard', 'Amsterdam', '', 'Senior Software Developer (m/v)', 'Vast', 'WO, HBO', '', '', 'Goede primaire en secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Software-Developer-mv/9114031/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('197', '8597907', 'ItJobboard', 'Amsterdam', '', 'Business Intelligence Professional - ( SQL, MicroStrategy, BI ) - Amsterdam', 'Vast', 'HBO', '', '', '€0 - €60.000 per jaar', null, 'http://www.itjobboard.nl/ICT-baan/Business-Intelligence-Professional-SQL-MicroStrategy-BI-Amsterdam/8597907/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('198', '9114791', 'ItJobboard', 'Veldhoven', '', 'SharePoint Developer', 'Vast', 'Onbekend', '', '', 'Good employment conditions', null, 'http://www.itjobboard.nl/ICT-baan/SharePoint-Developer/9114791/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('199', '9123043', 'ItJobboard', 'Amsterdam, Rotterdam, Utrecht, Den Bosch, Eindhoven', '', 'Manager Technology ( IT Manager ) - Amsterdam', 'Vast', 'Onbekend', '', '', 'uitstekende voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Manager-Technology-IT-Manager-Amsterdam/9123043/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('200', '9040657', 'ItJobboard', 'Amsterdam', '', 'Developer', 'Vast', 'WO, HBO', '', '', 'Een goed salaris en passende secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Developer/9040657/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('201', '9094590', 'ItJobboard', 'Enschede, Eindhoven, Amsterdam, Utrecht, Apeldoorn, Zwolle, Den Bosch, Maastricht', '', 'Test Engineer ( Tester / Engineer )', 'Vast', 'HBO', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/Test-Engineer-Tester-Engineer-/9094590/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('202', '9055964', 'ItJobboard', 'Regio Utrecht', '', 'Java Front End Developer', 'Vast', 'HBO', '', '', 'Een goed salaris en passende secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Java-Front-End-Developer/9055964/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('203', '9114654', 'ItJobboard', 'Amersfoort - Utrecht - Amsterdam - Den Bosch', '', 'Tester / documentalist ( Testing / Test Analyst / Test Coördinator )', 'Vast', 'HBO, MBO', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/Tester-documentalist-Testing-Test-Analyst-Test-Co%C3%B6rdinator-/9114654/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('204', '9094595', 'ItJobboard', 'Enschede, Eindhoven, Amsterdam, Utrecht, Apeldoorn, Zwolle, Den Bosch, Maastricht', '', 'C# Software Engineer / Developer / Ontwikkelaar', 'Vast', 'HBO', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/C-Software-Engineer-Developer-Ontwikkelaar/9094595/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('205', '8911373', 'ItJobboard', 'Amsterdam, Best, Deventer, Groningen, Rotterdam en Vianen', '', 'ICT Starter / Young Professional / Trainee', 'Vast', 'HBO', '', '', 'Uitstekende arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/ICT-Starter-Young-Professional-Trainee/8911373/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('206', '9111706', 'ItJobboard', 'Utrecht', '', 'Junior Configuratie Manager', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Junior-Configuratie-Manager/9111706/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('207', '9055968', 'ItJobboard', 'Amsterdam', '', 'Senior System Engineer van UNIX/Java', 'Vast', 'HBO', '', '', 'Een goed salaris en passende secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Senior-System-Engineer-van-UNIXJava/9055968/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('208', '9123031', 'ItJobboard', 'Amsterdam, Rotterdam, Utrecht, Den Bosch, Eindhoven', '', 'Senior Associate Risk Assurance - Amsterdam ( IT, Operational Audits, Risk Management of Accountancy )', 'Vast', 'WO', '', '', 'uitstekende voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Associate-Risk-Assurance-Amsterdam-IT-Operational-Audits-Risk-Management-of-Accountancy-/9123031/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('209', '9067028', 'ItJobboard', 'Antwerpen', '', '(Senior) WEB DEVELOPER (PHP / JAVASCRIPT) - Antwerpen (Wilrijk)', 'Vast', 'Onbekend', '', '', 'Competitive', null, 'http://www.itjobboard.nl/ICT-baan/Senior-WEB-DEVELOPER-PHP-JAVASCRIPT-Antwerpen-Wilrijk/9067028/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('210', '9111708', 'ItJobboard', 'Utrecht', '', 'Junior Testdata Specialist', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Junior-Testdata-Specialist/9111708/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('211', '9108250', 'ItJobboard', 'Diemen', '', 'Projectmanager IT Bancair', 'Freelance', 'WO, HBO', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Projectmanager-IT-Bancair/9108250/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('212', '9082951', 'ItJobboard', 'Nieuwegein', '', 'Frontend developer (Javascript, HTML4-5, CSS3, jQuery en Bootstrap)', 'Vast', 'HBO', '', '', 'Aantrekkelijke secundaire voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Frontend-developer-Javascript-HTML45-CSS3-jQuery-en-Bootstrap/9082951/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('213', '9103741', 'ItJobboard', 'Venlo', '', 'ICT Infrastructure Architect', 'Vast', 'Onbekend', '', '', 'in overleg', null, 'http://www.itjobboard.nl/ICT-baan/ICT-Infrastructure-Architect/9103741/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('214', '9030667', 'ItJobboard', 'Amsterdam', '', 'Network Design Engineer', 'Vast', 'HBO', '', '', 'Aantrekkelijke secundaire voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Network-Design-Engineer/9030667/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('215', '9100366', 'ItJobboard', 'Hinxton, near Cambridge', '', 'Software Engineer', 'Freelance', 'Onbekend', '', '', 'Competitive', null, 'http://www.itjobboard.nl/ICT-baan/Software-Engineer/9100366/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('216', '9111703', 'ItJobboard', 'Utrecht', '', 'Junior Beheerder Unified Communications', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Junior-Beheerder-Unified-Communications/9111703/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('217', '9094604', 'ItJobboard', 'Enschede, Eindhoven, Amsterdam, Utrecht, Apeldoorn, Zwolle, Den Bosch, Maastricht', '', 'EMBEDDED SOFTWARE ENGINEER', 'Vast', 'WO, HBO', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/EMBEDDED-SOFTWARE-ENGINEER/9094604/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('218', '9111704', 'ItJobboard', 'Utrecht', '', 'Junior Performance Engineer', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Junior-Performance-Engineer/9111704/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('219', '9117281', 'ItJobboard', 'Hilversum', '', '.NET ontwikkelaar / Developer (OOP, SQL, C#)', 'Vast', 'Onbekend', '', '', 'Goede (secundaire) arbeidsvoorwaarden (premievrij pensioen, 30 vakantiedagen).', null, 'http://www.itjobboard.nl/ICT-baan/NET-ontwikkelaar-Developer-OOP-SQL-C/9117281/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('220', '9022503', 'ItJobboard', 'Nieuwegein', '', 'Linux / Unix-beheerder v/m', 'Vast', 'Onbekend', '', '', 'Aantrekkelijke secundaire voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Linux-Unixbeheerder-vm/9022503/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('221', '8961636', 'ItJobboard', 'Landelijk', '', 'Senior Windows Systeem beheerder (Citrix, XenApp, SCCM. en MCSE)', 'Vast', 'Onbekend', '', '', 'Juiste beloningen en vergoedingen', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Windows-Systeem-beheerder-Citrix-XenApp-SCCM-en-MCSE/8961636/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('222', '9084930', 'ItJobboard', 'Amsterdam', '', 'Technical Solution Manager', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Technical-Solution-Manager/9084930/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('223', '9061256', 'ItJobboard', 'Amsterdam', '', 'Linux Software Architect ( PHP and C++ ) - Programmeur / Developer / Ontwikkelaar - Amsterdam', 'Vast', 'Onbekend', '', '', 'Excellent salary', null, 'http://www.itjobboard.nl/ICT-baan/Linux-Software-Architect-PHP-and-C-Programmeur-Developer-Ontwikkelaar-Amsterdam/9061256/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('224', '9108398', 'ItJobboard', '\'s-Hertogenbosch', '', 'Ervaren Senior Systeembeheerder', 'Vast', 'HBO', '', '', '€ 3394,- bruto per maand', null, 'http://www.itjobboard.nl/ICT-baan/Ervaren-Senior-Systeembeheerder/9108398/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('225', '9021035', 'ItJobboard', 'Amsterdam', '', 'Integration Developer @ IMC asset management', 'Vast', 'Onbekend', '', '', 'VB', null, 'http://www.itjobboard.nl/ICT-baan/Integration-Developer-IMC-asset-management/9021035/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('226', '8255276', 'ItJobboard', 'Amsterdam', '', 'Senior C++ Market Connectivity Developer', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/Senior-C-Market-Connectivity-Developer/8255276/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('227', '8487143', 'ItJobboard', 'Amsterdam', '', 'Senior C++ Automated Trading System Developer', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/Senior-C-Automated-Trading-System-Developer/8487143/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('228', '8977697', 'ItJobboard', 'Landelijk', '', 'Werkplekbeheerder, Landelijk', 'Vast', 'MBO', '', '', 'Juiste beloningen en vergoedingen', null, 'http://www.itjobboard.nl/ICT-baan/Werkplekbeheerder-Landelijk/8977697/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('229', '9058846', 'ItJobboard', 'Den Haag', '', 'Manager IT Operations', 'Vast', 'Onbekend', '', '', 'Good employment conditions', null, 'http://www.itjobboard.nl/ICT-baan/Manager-IT-Operations/9058846/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('230', '9084935', 'ItJobboard', 'Amsterdam', '', 'Windows Intaker / Packager', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Windows-Intaker-Packager/9084935/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('231', '9121053', 'ItJobboard', 'Bergen op Zoom', '', 'Business Analist Business Intelligence', 'Vast', 'Onbekend', '', '', '€ 50K - € 65K op jaarbasis', null, 'http://www.itjobboard.nl/ICT-baan/Business-Analist-Business-Intelligence/9121053/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('232', '9097049', 'ItJobboard', 'Enschede, Eindhoven, Amsterdam, Utrecht, Apeldoorn, Zwolle, Den Bosch, Maastricht', '', 'starting Technical Software Engineer', 'Vast', 'Onbekend', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/starting-Technical-Software-Engineer/9097049/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('233', '9061258', 'ItJobboard', 'Amsterdam', '', 'Marketing Technology Executive IT - Amsterdam', 'Vast', 'Onbekend', '', '', 'Excellent salary', null, 'http://www.itjobboard.nl/ICT-baan/Marketing-Technology-Executive-IT-Amsterdam/9061258/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('234', '8476307', 'ItJobboard', 'Amsterdam', '', 'Trading Application Engineer', 'Vast', 'WO, HBO', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/Trading-Application-Engineer/8476307/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('235', '8917213', 'ItJobboard', 'Amsterdam', '', 'Senior C# Developer (UI side)', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/Senior-C-Developer-UI-side/8917213/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('236', '9107236', 'ItJobboard', 'Amsterdam', '', 'Senior SAP Business Support Analyst', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Senior-SAP-Business-Support-Analyst/9107236/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('237', '8977701', 'ItJobboard', 'Landelijk', '', 'Application Packager / Scripter, Landelijk', 'Vast', 'HBO, MBO', '', '', '2400-3500 bruto p/m', null, 'http://www.itjobboard.nl/ICT-baan/Application-Packager-Scripter-Landelijk/8977701/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('238', '9106108', 'ItJobboard', 'Amsterdam', '', 'Solution Architect', 'Vast', 'WO', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Solution-Architect/9106108/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('239', '8874388', 'ItJobboard', '', '', 'Systems Monitoring Engineer', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/Systems-Monitoring-Engineer/8874388/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('240', '9111691', 'ItJobboard', 'Amsterdam', '', 'Netwerk beheerder (Network Administrator / Engineer ) - Amsterdam', 'Freelance', 'Onbekend', '', '', 'uitstekende voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Netwerk-beheerder-Network-Administrator-Engineer-Amsterdam/9111691/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('241', '9061251', 'ItJobboard', 'Amsterdam', '', 'Software Architect / Developer / Programmeur - Ontwikkelaar ( C++ / PHP ) - Amsterdam', 'Vast', 'Onbekend', '', '', 'Excellent salary', null, 'http://www.itjobboard.nl/ICT-baan/Software-Architect-Developer-Programmeur-Ontwikkelaar-C-PHP-Amsterdam/9061251/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('242', '9061252', 'ItJobboard', 'Amsterdam', '', 'Big Data Architect ( software / developer/ programmeur / ontwikkelaar ) - Amsterdam', 'Vast', 'Onbekend', '', '', 'Excellent salary', null, 'http://www.itjobboard.nl/ICT-baan/Big-Data-Architect-software-developer-programmeur-ontwikkelaar-Amsterdam/9061252/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('243', '9120921', 'ItJobboard', 'Antwerp', '', 'RS3/ DeltaV Automation Engineer', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/RS3-DeltaV-Automation-Engineer/9120921/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('244', '9061249', 'ItJobboard', 'Amsterdam', '', 'Software Architect JavaScript / CSS / HTML5 ( Developer / Ontwikkelaar / Programmeur ) - Amsterdam', 'Vast', 'Onbekend', '', '', 'Excellent salary', null, 'http://www.itjobboard.nl/ICT-baan/Software-Architect-JavaScript-CSS-HTML5-Developer-Ontwikkelaar-Programmeur-Amsterdam/9061249/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('245', '9097042', 'ItJobboard', 'Utrecht', '', 'Embedded Software Engineer', 'Vast', 'WO, HBO', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/Embedded-Software-Engineer/9097042/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('246', '9094586', 'ItJobboard', 'Enschede, Eindhoven, Amsterdam, Utrecht, Apeldoorn, Zwolle, Den Bosch, Maastricht', '', 'Technische Software Engineer', 'Vast', 'HBO', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/Technische-Software-Engineer/9094586/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('247', '9097041', 'ItJobboard', 'Enschede, Eindhoven, Amsterdam, Utrecht, Apeldoorn, Zwolle, Den Bosch, Maastricht', '', 'Mechanical Engineer', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Mechanical-Engineer/9097041/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('248', '9059880', 'ItJobboard', 'Amsterdam, Rotterdam, Den Haag, Utrecht, Eindhoven', '', 'Medior Java Developer / Ontwikkelaar / Programmeur', 'Vast', 'HBO', '', '', 'Uitstekende primaire- en secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Medior-Java-Developer-Ontwikkelaar-Programmeur/9059880/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('249', '9083170', 'ItJobboard', 'Gouda', '', 'Senior Delphi Ontwikkelaar', 'Vast', 'HBO', '', '', 'Aantrekkelijke secundaire voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Delphi-Ontwikkelaar/9083170/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('250', '9112486', 'ItJobboard', '', '', 'Virtualization Specialist with VMware expertise', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Virtualization-Specialist-with-VMware-expertise/9112486/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('251', '9104725', 'ItJobboard', 'Amsterdam', '', 'Project Manager External IT Development', 'Vast', 'Onbekend', '', '', 'Excellent', null, 'http://www.itjobboard.nl/ICT-baan/Project-Manager-External-IT-Development/9104725/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('252', '9110271', 'ItJobboard', 'Amsterdam', '', 'Software Engineer / Developer / Ontwikkelaar ( Linux - Big Data ) - Amsterdam', 'Vast', 'WO, HBO', '', '', 'uitstekende voorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Software-Engineer-Developer-Ontwikkelaar-Linux-Big-Data-Amsterdam/9110271/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('253', '9104726', 'ItJobboard', 'Beerse', '', 'Project Manager', 'Freelance', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Project-Manager/9104726/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('254', '9110269', 'ItJobboard', 'Amsterdam', '', 'Linux Internal Engineer ( Support ) - Amsterdam', 'Vast', 'Onbekend', '', '', 'zeer aantrekkelijk', null, 'http://www.itjobboard.nl/ICT-baan/Linux-Internal-Engineer-Support-Amsterdam/9110269/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('255', '9031948', 'ItJobboard', 'Netherlands ( Laren, Utrecht, Amsterdam, Hilversum, Almere )', '', 'Business Intelligence Consultant / Developer (BI / data integrator / integratie )', 'Vast', 'Onbekend', '', '', 'VB', null, 'http://www.itjobboard.nl/ICT-baan/Business-Intelligence-Consultant-Developer-BI-data-integrator-integratie-/9031948/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('256', '9087813', 'ItJobboard', 'Amsterdam, Hoorn, Utrecht, Eindhoven, Rotterdam', '', 'Junior Technisch Applicatiebeheerder', 'Vast', 'Onbekend', '', '', 'Goede arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Junior-Technisch-Applicatiebeheerder/9087813/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('257', '9117684', 'ItJobboard', 'Amersfoort', '', 'Senior IT/ Business Projectmanager', 'Vast', 'Onbekend', '', '', 'Uitstekende arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Senior-IT-Business-Projectmanager/9117684/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('258', '8941264', 'ItJobboard', 'Amsterdam', '', 'Functional Application Coordinator (Functioneelbeheerder) - Amsterdam', 'Vast', 'Onbekend', '', '', 'Competitive', null, 'http://www.itjobboard.nl/ICT-baan/Functional-Application-Coordinator-Functioneelbeheerder-Amsterdam/8941264/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('259', '9102184', 'ItJobboard', 'amsterdam', '', 'Senior Solution Architect', 'Vast', 'Onbekend', '', '', '', null, 'http://www.itjobboard.nl/ICT-baan/Senior-Solution-Architect/9102184/nl/?xc=246&amp;Currency=EUR&amp;source=Search');
INSERT INTO `test` VALUES ('260', '9059889', 'ItJobboard', 'Amsterdam, Rotterdam, Den Haag, Utrecht, Eindhoven', '', 'Embedded Software Specialist / Engineer / Developer / Programmeur', 'Vast', 'HBO', '', '', 'Uitstekende primaire- en secundaire arbeidsvoorwaarden', null, 'http://www.itjobboard.nl/ICT-baan/Embedded-Software-Specialist-Engineer-Developer-Programmeur/9059889/nl/?xc=246&amp;Currency=EUR&amp;source=Search');

-- ----------------------------
-- Procedure structure for test_multi_sets
-- ----------------------------
DROP PROCEDURE IF EXISTS `test_multi_sets`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `test_multi_sets`()
    DETERMINISTIC
begin
        select user() as first_col;
        select user() as first_col, now() as second_col;
        select user() as first_col, now() as second_col, now() as third_col;
        end
;;
DELIMITER ;
